spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mysql
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver